### ISSUE TITLE
Suggestion: Hide all tweets/replies/etc from verified accounts

### ISSUE THREAD

**Issue by soulscythe** [insin/control-panel-for-twitter#145]
Given the changes to twitter's verification system, the type of people to actually be verified are not so much the type that I actually care to see the posts of, and this might be an opinion shared by many others. 

An option to filter out anything posted by a verified account would be neat. The feature could also include some sort of whitelisting, but either way would be a good addition I feel.

(Great work btw)

**Comment by yoshimo** [comment]
The majority of people that are verified did not pay but got that mark before this change was suggested by the new owner.
It gives credibility to journalists,  activists and institutions and politicians and prevents people from easily impersonate them.
I think this suggestion does more harm than good and I could imagine that twitter won't  implement  this ad planned.

**Comment by insin** [comment]
Do you mean the new "Official" label or blue ticks?

You can already use the "Verified accounts" setting in the Experiments section of the options page to highlight or hide blue ticks and interactions with them (which I just noticed was broken, should be fixed in v2.15.6)

**Comment by insin** [comment]
This would be useful in tweet threads now Twitter Blue replies are being boosted, sometimes it's just pages of them in no particular order

**Comment by mikkelens** [comment]
Bumping because this seems to still be broken? It is at the very least unclear if the setting blindly targets all checkmarks, legacy (from database?) checkmarks or just "blue" checkmarks. I've got it on but I still see Twitter Blue posts.

**Comment by insin** [comment]
The current experimental setting was for actual verified accounts, so it does nothing now
